apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-config-cli-secret
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-store
    kind: ClusterSecretStore
  target:
    name: keycloak-config-cli-secret
  data:
    - secretKey: ARGOCD_CLIENT_SECRET
      remoteRef:
        key: argocd-keycloak-secret-source
        property: clientSecret
    - secretKey: BACKSTAGE_CLIENT_SECRET
      remoteRef:
        key: backstage-keycloak-secret-source
        property: clientSecret
    - secretKey: PLATFORM_ADMIN_PASSWORD
      remoteRef:
        key: keycloak-platform-admin-source
        property: password
