apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:okccl/platform-gitops.git
    targetRevision: HEAD
    path: platform/secrets/config
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: external-secrets.io
      kind: ClusterExternalSecret
      jsonPointers:
        - /spec/externalSecretSpec/data/0/remoteRef/conversionStrategy
        - /spec/externalSecretSpec/data/0/remoteRef/decodingStrategy
        - /spec/externalSecretSpec/data/0/remoteRef/metadataPolicy
        - /spec/externalSecretSpec/data/0/remoteRef/nullBytePolicy
        - /spec/externalSecretSpec/data/1/remoteRef/conversionStrategy
        - /spec/externalSecretSpec/data/1/remoteRef/decodingStrategy
        - /spec/externalSecretSpec/data/1/remoteRef/metadataPolicy
        - /spec/externalSecretSpec/data/1/remoteRef/nullBytePolicy
        - /spec/externalSecretSpec/data/2/remoteRef/conversionStrategy
        - /spec/externalSecretSpec/data/2/remoteRef/decodingStrategy
        - /spec/externalSecretSpec/data/2/remoteRef/metadataPolicy
        - /spec/externalSecretSpec/data/2/remoteRef/nullBytePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
