apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/okccl/platform-gitops.git
    targetRevision: HEAD
    path: platform/secrets/config
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: external-secrets.io
      kind: ClusterExternalSecret
      jqPathExpressions:
        - .spec.externalSecretSpec.data[].remoteRef.conversionStrategy
        - .spec.externalSecretSpec.data[].remoteRef.decodingStrategy
        - .spec.externalSecretSpec.data[].remoteRef.metadataPolicy
        - .spec.externalSecretSpec.data[].remoteRef.nullBytePolicy
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.data[].remoteRef.nullBytePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
