apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-config-cli
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://jkroepke.github.io/helm-charts
      chart: keycloak-config-cli
      targetRevision: 1.3.7
      helm:
        valueFiles:
          - $values/platform/keycloak/config-cli-values.yaml
    - repoURL: https://github.com/okccl/platform-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/okccl/platform-gitops.git
      targetRevision: main
      path: platform/keycloak/config-cli
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .metadata.annotations["force-sync"]
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.data[].remoteRef.nullBytePolicy
