apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-routes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:okccl/platform-gitops.git
    targetRevision: HEAD
    path: platform/gateway/routes/keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.parentRefs[]?.group
        - .spec.parentRefs[]?.kind
        - .spec.rules[]?.backendRefs[]?.group
        - .spec.rules[]?.backendRefs[]?.kind
        - .spec.rules[]?.backendRefs[]?.weight
