apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/okccl/platform-gitops.git
    targetRevision: main
    path: platform/keycloak/db-config
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /spec/bootstrap
        - /spec/externalClusters
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.data[].remoteRef.nullBytePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
