apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: kyverno-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ccl-labs/platform-gitops.git
    targetRevision: main
    path: platform/policy/policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
