apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-secrets-sources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ccl-labs/platform-gitops.git
    targetRevision: HEAD
    path: platform/secrets/sources
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
