image:
  tag: "6.5.0-26.5.4"

annotations:
  argocd.argoproj.io/sync-wave: "6"

env:
  KEYCLOAK_URL: http://keycloak-keycloakx-http.keycloak.svc.cluster.local:80/auth
  KEYCLOAK_USER: admin
  KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
  KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
  IMPORT_FILES_LOCATIONS: /config/*
  IMPORT_VAR_SUBSTITUTION_ENABLED: "true"

existingSecret: keycloak-admin-credentials
existingSecretKey: password

extraEnv:
  - name: ARGOCD_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: keycloak-config-cli-secret
        key: ARGOCD_CLIENT_SECRET
  - name: BACKSTAGE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: keycloak-config-cli-secret
        key: BACKSTAGE_CLIENT_SECRET
  - name: PLATFORM_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-config-cli-secret
        key: PLATFORM_ADMIN_PASSWORD
  - name: APP_DEVELOPER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-config-cli-secret
        key: APP_DEVELOPER_PASSWORD

existingConfigMap: keycloak-config-cli-realm

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
