apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ccl-labs/platform-gitops.git
    targetRevision: HEAD
    path: platform/gateway/config
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.parentRefs[]?.group
        - .spec.parentRefs[]?.kind
        - .spec.rules[]?.backendRefs[]?.group
        - .spec.rules[]?.backendRefs[]?.kind
        - .spec.rules[]?.backendRefs[]?.weight
    - group: gateway.networking.k8s.io
      kind: Gateway
      jqPathExpressions:
        - .spec.listeners[]?.tls?.certificateRefs[]?.group
        - .spec.listeners[]?.tls?.certificateRefs[]?.kind
