apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-keycloak-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-store
    kind: ClusterSecretStore
  target:
    name: argocd-keycloak-secret
  data:
    - secretKey: clientSecret
      remoteRef:
        key: argocd-keycloak-secret-source
        property: clientSecret
