apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: fake-store
spec:
  provider:
    fake:
      data:
        - key: /demo/password
          value: supersecret
          version: v1
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubernetes-store
spec:
  provider:
    kubernetes:
      remoteNamespace: platform-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: argocd
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
