apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://backstage.github.io/charts
      chart: backstage
      targetRevision: 2.6.3
      helm:
        valueFiles:
          - $values/platform/backstage/values.yaml
    - repoURL: git@github.com:okccl/platform-gitops.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:okccl/platform-gitops.git
      targetRevision: main
      path: platform/backstage/app-config
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/data/0/remoteRef/conversionStrategy
        - /spec/data/0/remoteRef/decodingStrategy
        - /spec/data/0/remoteRef/metadataPolicy
        - /spec/data/0/remoteRef/nullBytePolicy
        - /spec/data/1/remoteRef/conversionStrategy
        - /spec/data/1/remoteRef/decodingStrategy
        - /spec/data/1/remoteRef/metadataPolicy
        - /spec/data/1/remoteRef/nullBytePolicy
        - /spec/data/2/remoteRef/conversionStrategy
        - /spec/data/2/remoteRef/decodingStrategy
        - /spec/data/2/remoteRef/metadataPolicy
        - /spec/data/2/remoteRef/nullBytePolicy
