apiVersion: v1
kind: Secret
metadata:
    name: argocd-keycloak-secret-source
    namespace: platform-secrets
stringData:
    clientSecret: ENC[AES256_GCM,data:jYKxlpghjSsGpscbpn/849VRiHbdoApESLtMNFrhiEk=,iv:2h0r4EpHEvqtXbKfJRlyaUGzxBm2mU0AMVJAJ/hveko=,tag:aUtX24PITF6IqxpsPRHLSQ==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMFFibTgvTFhHT0VVRWRp
            MVB0aGpPZmlEdEt3ZkxldEpaWkFQT2dROENvCm9JNm5nUFpQNWFkY2pKdnR1QlF1
            bUtNMHNzUFk4aDgzTG9Dc1hWMW9vcG8KLS0tIEpLanlqTGl3MWZVLzdHUFdQbnFF
            eVJGTFRjZ3p6czhOUnZyMy9NaXBEYkkK3FHpofbyc+v8WgKDwyaJKPV5/BhHc9OS
            GLvrk8KSHqf4d3tNORrtcQAjmRtMFGlfCK0rmZrDaIc6xjnQEjtX6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T03:27:10Z"
    mac: ENC[AES256_GCM,data:H6m69aQoJe/X2tUyPfPzyL3b5X7xcL8adbbZSAVAxRhczrNe/92FqpgLMLRV5ZmEieYOymIxOMviwb2Kj95RmRu8Q7qwEwpPKXdBLlWGJjztEw/SK15hERxWO6rt4vbhHMutZ4F+xIW+SSponuUUnr4+14okQczp6Y6AT/GuDgA=,iv:lToL8sqnQ0As0rH1vgWdiJ2PyZR0JfU+4MP2Hm4DfdQ=,tag:MIcJrFz/NLuKL1xBi7lr8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
