apiVersion: v1
kind: Secret
metadata:
    name: backstage-secret-source
    namespace: platform-secrets
type: Opaque
stringData:
    BACKEND_SECRET: ENC[AES256_GCM,data:F1V0VnnchIBv+fCXqRF+YbeM1eIamYvAG8qhBvP4bx112WQRYLpsKb7ptU46hvf8Rz69UtIMQRmatYwqxSkliQ==,iv:LMxY/sTvyjetZb8GsBWeT7nMZDnWyAlBwOAQ3xLnk3Q=,tag:r3FTHoKuCVF4HSmYNRtfkQ==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SFhjaWxDMjFnZ0FNSUgz
            dzFTelk2dnJkUEtGaWViZ01ieEtOZi82MURnClVHWHg2RU80TklSdGFNUzZHMzh5
            d2RkSUdVMzk0N3gvOGo5RVBobEJzNUUKLS0tIDk1ZHRUUzNUeWYycy9YZnZQQS9i
            TS9NR0dMR3lTdFgrOWJ2WHNpNTJLSlkK5KrVmputJ7dXl0OI9IQL6pxP6hrIMSXy
            xkVPlqvIR1GfCK7FDHHnmWfCjCkVCxFFDGHBVGr3W7j1r3fUSgE6/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T03:27:11Z"
    mac: ENC[AES256_GCM,data:2fncvmcrO0i4mZZlEL1qAz5gEVX39bCbBivLLwx9MjlgnMXY+l3wA+s8zPXwuszjog5zVOMveCkt2d4+7aDgfq90BnYZpVnrsIJcifKouJU2FxYI6OwFw4JY/1WADIaY+RJoNyYDXQR4fic6Y88WjrIyHDZaMoxOlJrWtq2Q3GA=,iv:PWdu7vr4FhA4E6/XWFMqU7kTmMt90JQrkmFToWEtGQw=,tag:fjIdv3wtDXiGTAXwJeaeBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
