apiVersion: v1
kind: Secret
metadata:
    name: backstage-github-token-source
    namespace: platform-secrets
stringData:
    token: ENC[AES256_GCM,data:hr6A+fwnRzdEyLdcLVKnmaVxlbipcpiihbcbZQbu+0MDoGf6ACRbVQ==,iv:Nw5F6xHuOrM/HVZ550u+4tjXy46WG0bTO0SWefzoMro=,tag:ZVUQ9mdWwiPKrHBYcgeHxA==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTnFsRndyV3I0M2g1YjRq
            ZXdEUVk4T3FOMWFkaUVsM0UzVXRNajBMRmxJCkNzZk9PMXFocW5aZWxYRFdoRFVS
            eC92YkpiSGMyREhPN0ZMc3FHRjlnR0kKLS0tIHJqdVd1dTVldEZadlE2amhxUFVN
            Y3VsbVFEOEZCVXc2ZVZBVlVhak9KdEUKp/+N7PCSeZzLQMhnzkRrSxEOuoeOTF3v
            Nc6uycK81Dk7614Css79zv2KDIPs1rvGhnGu4ksvul0jhpIrpRJFHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T03:27:10Z"
    mac: ENC[AES256_GCM,data:e1U0TgxBYYCgiVUKck2UpC1sNtMxb/FA//7NNEkDu0sG0+bwRW0stsfDEjciNvnOdm11MZ6tczJ4WIWDmeGik+xFjzUcjL44zCQb9vxE2KalOj5IrapUSVMW4F9UBNQq6f82mxXEUkiAx5wOgE+uDhLH9TX1E3Kos1DOUVEc6ds=,iv:pBxAr/KClBiLzzNXVroo0T7LE/rEOQc4uO9QAs7YvBs=,tag:RgMGmxFIkZZo2HX/RIz8Ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
