apiVersion: v1
kind: Secret
metadata:
    name: backstage-keycloak-secret-source
    namespace: platform-secrets
stringData:
    clientSecret: ENC[AES256_GCM,data:RfHRIr1Iv8SiJtCksDd0D61c0sfOKjCJtQzzQuGObAc=,iv:1bMElVvwHYeDDs8llaRVDu9/S1EVaSoo/X5kODYqYJY=,tag:Rp7R2Y01kY43TdtyY/EieQ==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUnUwaEtpeFJQNG5OY0Ru
            cGFIWmlPVGt5R1NxZkpCY01rVUhZZHlJMlZFClBPeU5FQmFMMEQrQXhVRXBORThO
            VXJJc00rZFo5aGd6N0hlaDlMb2t5ZFEKLS0tIHh0QklrVTA0bHlFRHlncVUvTVZJ
            dFVBZVdENHU4VlJOME1UNnI1ZkU0ZVkKF2jTPQCMMLJm6qmJ7dPNo4pyt5YlBA7N
            rm4+pEjxrJE4HT9WmhHmSKwjt8t2K+QDdf8X3lWgrIgIIyGv0lf0KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T03:27:10Z"
    mac: ENC[AES256_GCM,data:/jryEkgLnOiQmEzZnEcyVjDtKBLWjdRqsljh959tjPp4M2LjQ3a7oq+nQi3nLF39YeyRwy5neMR+cReh880yDvhJB3p+vymifo4iyzHsFplcwU/kHt14ay5ed/NI5SEZ7SLxFMxcfnFuRn+84B9FPCEBUHrPj1WH6kmEl2R2iOw=,iv:0ScuJY8D7ekrsrUHQuI7rZMTG8GzGt1buoJ9bHUBqwc=,tag:Nn57q8s9a6wBavd5ZEY43w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
