apiVersion: v1
kind: Secret
metadata:
    name: backstage-secret-source
    namespace: platform-secrets
type: Opaque
stringData:
    BACKEND_SECRET: ENC[AES256_GCM,data:F1V0VnnchIBv+fCXqRF+YbeM1eIamYvAG8qhBvP4bx112WQRYLpsKb7ptU46hvf8Rz69UtIMQRmatYwqxSkliQ==,iv:LMxY/sTvyjetZb8GsBWeT7nMZDnWyAlBwOAQ3xLnk3Q=,tag:r3FTHoKuCVF4HSmYNRtfkQ==,type:str]
    ARGOCD_TOKEN: ENC[AES256_GCM,data:Lddw74gtuHH3u+BOCs/u8OZP7ScL/XDEMGZuPz6EElE2bBbhyxTiy5zjrAVRfiYZUCzmIm9o5T6Q5dT+D7zzzFXolzKOE6mYEjgUXA4W4bKAEKNunDc0DmlcMI3iGSynxiTgYM18N8HLc4kfcFeq0y9wUyUHjatJiuI2HMhZW7E6Otoi39lruDSW0an909XDrKBjklHiO5MpdawrZRc+hCfy+7ECtsvNUlxa7iynaG2fVRkZJoieFSK4YVNJm81bPgG6TMlOvo4a60fwY/fT8YdbVRlDpQU+cZvL24RHn/0XnM6C8mll7l6j8DiL1n8D8Q==,iv:qfIQ9gViKnCV92osEZrcYf71wmLWSaQ6MKNz70aHcFY=,tag:DAYKi+A6minhPkaj0vFxOw==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SFhjaWxDMjFnZ0FNSUgz
            dzFTelk2dnJkUEtGaWViZ01ieEtOZi82MURnClVHWHg2RU80TklSdGFNUzZHMzh5
            d2RkSUdVMzk0N3gvOGo5RVBobEJzNUUKLS0tIDk1ZHRUUzNUeWYycy9YZnZQQS9i
            TS9NR0dMR3lTdFgrOWJ2WHNpNTJLSlkK5KrVmputJ7dXl0OI9IQL6pxP6hrIMSXy
            xkVPlqvIR1GfCK7FDHHnmWfCjCkVCxFFDGHBVGr3W7j1r3fUSgE6/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T23:27:14Z"
    mac: ENC[AES256_GCM,data:yaoWb0q75xPNcpMEyucg/AiT1rYJA3yY4jjXj7KzD7l19SujaZbJwQJP3e6KzXOtohfKWqI2o28fnX/ZUfeCvnjtm6nZdCPBK+fpkGRUWD+VLK99A04+Jq8vfJ2XCkp3d3w+N68RxYDRjGfg4DqAKyHyR2nkNilkJyCy35CsRek=,iv:Ck6aVUQgot1eWVQbOq/nhCXy+wPOh46Ksmh07qdd70g=,tag:INQRRjcBTjB/luiSTEx6sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
