apiVersion: v1
kind: Secret
metadata:
    name: backstage-db-credentials-source
    namespace: platform-secrets
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:iDp/,iv:+qpTjE4ze851AxVw6de6HyLPsYfwt/n/ZrlSgAw25eA=,tag:ZzyKxPMqccCxZtVD6/7j9g==,type:str]
    password: ENC[AES256_GCM,data:xmnpfkZW3gxbpH+cqy/PWc1Qtf3+UeVCaAD3TkuicJs=,iv:N0A0RLc/r3m86WBUjRvAXbs6oi6uvsrfUExIVgNHBL0=,tag:kdQmI0+CVWK66bdsPr+ByA==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWXRBb1VoU29JdHdManRU
            YnRFZlg3eWhBMHBmVHY5dWM5cXFyRTBmWERFCllqTEgyaWZVemlmUm1mdE81VHdm
            REQxYVJCajB5NDB3LzV5OStqZkswc1UKLS0tIDhKd1ZVYVpUdzluU1RRVDdWQS8y
            TmVxbTYwek9udTJUdGQ2SThCWmN0bHMK33dHkgfqZZbVs9xr5MQ161kI6ZiAUYRP
            Wr8EN90pE9PpoCRygcH2kUJFhqBRZ2P9WGqCCL6vzFIY3f6t8naZ0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T03:27:10Z"
    mac: ENC[AES256_GCM,data:t39VqGLpqTmudQk3pVFwvDWvwUZrgxYD8Lk3pDYRHZ2beX99KQuq++9j7wnMDqAouT7TQxhjOHe1Y3xCiAv0W1YfVn014Za66R5o5cERsZ1MR+L7bkYwOLD9h9xXLhCUDWuyLl6Dws8Yl1LmZOntN/aCcvEQp2x3hYKeTLyhkoc=,iv:xanxaUEURn2e25EnAHZ9nQ61WQEz1Q4JP84+PeOLJaM=,tag:S6XnF0byeLiNieYom+3kVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
