apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret-source
    namespace: platform-secrets
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:JQHpf52YiERwJMLl27qI6WiMy9C7hVed1se+DY17ntXreBR4jb1MupeDomo7YA4mrPGTrDobHTYlf3OHQjvEQds5JpX7WORyFIh8TKf7ot4zcRgqM7VosnJu30KvWcB7GD08+q4HC4/FcfOay+HVgcuMAjhPQ0p9rJe2EQ==,iv:Dl+qQKV1aWWET3lexI2LLemQJCUMSdAIX0B5i1F6/R0=,tag:x1jYMGXzxfLTNKKyDcdd3Q==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPL0o4TlBKL0hBU2hadUJG
            aEJ5Yk5IaXJlRnZ2NDJIMXRrcmF0YVlNUkIwCjBrNVNPWGZTU21VcUNKNk00YVJQ
            L01ZNW9SZ2RZTTRPREtzNEJQT0Z0bjQKLS0tIFRiWXRoMzRSVXN6eFl2M205Z0RS
            dE94aldNKzJFdkFranduaGZISVQyTE0KwFnx5ewIsxP/v3QZPmIyztTYx5cx/8NM
            eQm4kXd73bGKGajCmXu4ujIphBbjnWQk2VouXxBYyr0Oa/YKgK8QKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T03:19:35Z"
    mac: ENC[AES256_GCM,data:kuDFISFXzYV9DQwhghs20lwqlCmLXI5F5ue4l25bmo0OtGDnXB+81L5FQNmdLrnl8xew1iupWgRLg7lXv+0lohd3V+2MTSWBFUWuSQ24H2ZIMBZqVzD/lemOB/T1FooJPrLxYz5GhLaW7WMqgf7X6DgdF5Xw6EIq2CaRPFNhH1c=,iv:dki4qTP061NEWJo69K/89JGUHr+wCGJYm/y7WR30N/w=,tag:nBrBd5A4nsAkLOAGWMm0pw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
