apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pat
    namespace: platform-secrets
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:IePl,iv:t9WqG+5xNNTajXHubPMYUn+kQqWKA9OA19gDSk2SvQ4=,tag:/2iILoIOjdHk0XSQnCiblQ==,type:str]
    password: ENC[AES256_GCM,data:l2oXcO1Nm6Xe6SvpwJ25Loi1Vv1TOkj9Gp7MgvN55tYh539fhJX2bA==,iv:59zLh8v5wbMrVnzE0lhxbKRz5Ak3X4opMe91ntOIkTU=,tag:MvPH+gL2lni3F69s2op0/Q==,type:str]
    email: ENC[AES256_GCM,data:j+TIatf7AUyICAOfnSAM8EdE,iv:OITChoJKLe0fqs8fUcgFytKvTJAzzzP7FliECdzG5AA=,tag:7eQmi+wNNPZ9FZtBVKWAZw==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aDVYOHFpVlY0VlVSMmZm
            WE9Hemw5dmU2OGRSMkNZZHpyMUFjbVg3WkFvClRqc2dyQ1dPWnorcWcrMEE5dzNv
            UW1YTHc5ZEU4dVljOWZLc0EwLzFKejQKLS0tIEhtMzVESFl1WVZPVzBlVy9tR2Q1
            M0J0a2FOUnh6RWJrSkIwMTRaNlZvdzgKk/1ShlJMS7q0H7p+JS3svQfnYJsPifQc
            DB6+pq5oF+PgCNRpwxOqMTwPD//1hDrbzXzBc2+nPXEY+4qgUm4c9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T03:27:11Z"
    mac: ENC[AES256_GCM,data:xj+MUQBS0BHiiq156jZymwvZzJagZs/TiuG8Ak3QBGbE/hR/6REWA6QtGLWSbr+6lkwkEhDoIOP9yopVm1ruy7w1y37OoO+TU+KAKOqr8hrKUSt/7dKiOAbxwx5xbowA8J0xZkpjIXiO3VIlYGWgV4pEyvBPYaz9zOmflLlOtNE=,iv:y2kcZPe/iO1L73AZhJKNv84eUkr+zSYPnVv1MCHrDJU=,tag:Wzn8cFlUf0M5BswH0QkLdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
