apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pat
    namespace: platform-secrets
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:75i4HR4=,iv:6CPOsipx4FsWFEBeEKvVpefVCFt5tj9hQxCKUZZlh3Q=,tag:gVezSJR6zPJdQMhvnzsYBg==,type:str]
    password: ENC[AES256_GCM,data:l2oXcO1Nm6Xe6SvpwJ25Loi1Vv1TOkj9Gp7MgvN55tYh539fhJX2bA==,iv:59zLh8v5wbMrVnzE0lhxbKRz5Ak3X4opMe91ntOIkTU=,tag:MvPH+gL2lni3F69s2op0/Q==,type:str]
    email: ENC[AES256_GCM,data:j+TIatf7AUyICAOfnSAM8EdE,iv:OITChoJKLe0fqs8fUcgFytKvTJAzzzP7FliECdzG5AA=,tag:7eQmi+wNNPZ9FZtBVKWAZw==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aDVYOHFpVlY0VlVSMmZm
            WE9Hemw5dmU2OGRSMkNZZHpyMUFjbVg3WkFvClRqc2dyQ1dPWnorcWcrMEE5dzNv
            UW1YTHc5ZEU4dVljOWZLc0EwLzFKejQKLS0tIEhtMzVESFl1WVZPVzBlVy9tR2Q1
            M0J0a2FOUnh6RWJrSkIwMTRaNlZvdzgKk/1ShlJMS7q0H7p+JS3svQfnYJsPifQc
            DB6+pq5oF+PgCNRpwxOqMTwPD//1hDrbzXzBc2+nPXEY+4qgUm4c9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T19:20:43Z"
    mac: ENC[AES256_GCM,data:fKwoW67gOAMJhY82Ucb7WmzRfwIUOVrL1IrQj7c6CYUuVuuxkQgG7alFLbwt7boqCyXZ58w7ohTMoJeFeNf7HEDeWhOj2jbSIspoDRsV9DRZ+luzTDTRQxKgqsXRgiLfuSzt7T9EM8BjcxeutwqF0EpSS6JsKun+gmxKP8vfLKw=,iv:4mjX7i+W1ecmKGyFzEM15KZPKW50dM3f+T9Aj9I0wDg=,tag:3m6mQ3cwiFIb4OcJI/zoKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
