apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-credentials-source
    namespace: platform-secrets
stringData:
    username: ENC[AES256_GCM,data:8ZRn51V3v1E=,iv:Ip8OlaoA1N7emljAS7Q2MBpXC704wIvLcCVsWeS0c1g=,tag:smDCBSITco5517UsvZMmJQ==,type:str]
    password: ENC[AES256_GCM,data:uV/WkgDxMyquRjgcf3kUqn7N9dA=,iv:ysA6IZ75FS9u2+vI2drjYdRz4qb/o0m93WoccJQZ9e4=,tag:fQGeoHaOvZnDHocG7FDwRQ==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLblQvSTF1U2dsL2IzaWJH
            T1VURUNqYkx5aUtoTEQxbmpBSWU5V1RoY0ZRCnpabWw1V2ZiMFc3RUFweGJTc04r
            TDViT2o1b2UrNVRybFFEYW1aSlNkd2cKLS0tIC9rdjYzOFNQWVIvOC8wbCtlWUlm
            OFNtZ1NZZ2gxQ0ZMaTF1ZzZrYmErejgK7az3YEaeFMNhb8jXXQaXtybjbFnNBqqq
            P5mBpu8bdg2HzmQPUhZtx9KCDY+Sz63SUey/o6x6VAUgU/7tMVL40w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T03:27:11Z"
    mac: ENC[AES256_GCM,data:eTs6l4wz+QiRllLbam6uDFTsPR6A0KYHKS9usyj/M9mCbD78Gai2jmS1UVc40aYqrpOT3kevcqXLQLewXUtQu5QO8k1dYpSLFcc4qC0Vhz9Hbuq6yyKZs6Rva4l0XxTyrjumy2ATUI8QPKVapIIfeFF6G8rPxkbAcyZ3VIX19es=,iv:7taZPVAJnVQ8K7eMITo9tEIQroomrnGy6hFMbDlZxc0=,tag:/81kY/K2Jbi9ajlKTm2WFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
