apiVersion: v1
kind: Secret
metadata:
    name: keycloak-app-developer-source
    namespace: platform-secrets
stringData:
    password: ENC[AES256_GCM,data:aeX6x46xzrutt16XHQ==,iv:1Tus7ZHIv/CqY+Fw6Fx3+u1jHv80B5qg0fHwzfW6Ki8=,tag:b59S2r/Hl6k7q0KiJ2dmtQ==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWM3SVJxbUZtYytXN2gy
            VFZObURhSmp3alg5OERjYlVqMHA0a2pJZFdvCjFuYnpjUmJJTmJia1QwZktRSmlX
            amhreEsydDFJc0RjcDJSKzJpRU9mcUkKLS0tIDE5UVBjK1hpR01FT3BpSk92cHIv
            aXBXc0pvakdzck1JQUhFVEpvbGpqSkUKiAGwwnvMxiyF8oUHYe8WTBT5g1i/ET5F
            iyupUcWUQq/4ZZcWZr6Cc4x6jpiPzAWmJaTR8QtTFgvFFgDg9t4ROg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T14:44:46Z"
    mac: ENC[AES256_GCM,data:+DMp505/viVqfu2kkr+Pd2o9/C8JWrr53FGU1RYdFsypOeXQ8/+qHKQYjaFAS55TiGb5xAkJeh7n78TEHLhkdOUTqpqFNsm29jMrVRkL5ezOjwnSWBqZuxyILpKO9m/0tBZG0nKb2aWwozJDXXeUg1Nc8NxyybQ+GfiBGTEIvvY=,iv:tE3DehS2sxbbh3gu/6SbJkGKEUZMc9qgeSh7mV6y3jc=,tag:UYlzSIoarciJ/QuvtxWNkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
