apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-credentials-source
    namespace: platform-secrets
stringData:
    password: ENC[AES256_GCM,data:ok45zcEnMbuJu+5yJ3dOSOypiXtXi64=,iv:C8q7NbQCew0MLNW1KR7Nz3YTjTspY7fToYJf9FDpM9U=,tag:9IgDAzKwMy0bj3qadkn2zg==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIY056bDRKcFNVckI4RDJU
            V1kzbVI2d0RDTXlTRFlvMGRzRWFlK25WL3k0ClkzMmRxYWxlLzJCWDkrSklrUzdP
            NHRSRlloTVY5ZG1VK1QvdVZPR2VlT0kKLS0tIDFUNHdleFlBTUpVbENyNGhQSVQw
            cEc0OEFnZ2lkL0R2RVpNMVBOQUtuaXMK7uuc7pCnzWRBIgKpw0wlLhGJlBXnNmgq
            mToSlsK4tfON0qpm7OGmuWp7VwTcHcXYah5mXyoOaPjh7A5otj38uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T03:27:11Z"
    mac: ENC[AES256_GCM,data:IvOZRAT2l3u+5ZzyMFRX7moJeYAuQsI1ePMoAsASssnuD5rQmd2MmbZ1KaC4R6dbgNd3t2REfXUDvZqZ9WKZCZIZfbABctoq4rNfy7O+E1Lj0yCAYVIDLejs+iLyvBVPk+N6y0iQ59KG0ZD2YIeyJw2YMmqwVtzStLyE885gUek=,iv:02tJm4XspVu9uI227cDqy3Lmr8Fsqaw2CDMEeRs5Jlo=,tag:8ghT7vAir1dZ1sBRIbilCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
