apiVersion: v1
kind: Secret
metadata:
    name: keycloak-platform-admin-source
    namespace: platform-secrets
stringData:
    password: ENC[AES256_GCM,data:+sxvPleMlyg=,iv:2MvreT9z5KOHqMLu84/wT1S7qRQ2ybqd5qXmTEScWhA=,tag:EtKhg01pNM6TumNJfoHYOQ==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWM3SVJxbUZtYytXN2gy
            VFZObURhSmp3alg5OERjYlVqMHA0a2pJZFdvCjFuYnpjUmJJTmJia1QwZktRSmlX
            amhreEsydDFJc0RjcDJSKzJpRU9mcUkKLS0tIDE5UVBjK1hpR01FT3BpSk92cHIv
            aXBXc0pvakdzck1JQUhFVEpvbGpqSkUKiAGwwnvMxiyF8oUHYe8WTBT5g1i/ET5F
            iyupUcWUQq/4ZZcWZr6Cc4x6jpiPzAWmJaTR8QtTFgvFFgDg9t4ROg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T03:27:11Z"
    mac: ENC[AES256_GCM,data:VdbNK6qz497jQJkHWTmnEjJiCWeUJmCGnyH1PYj7UHVKgtu5zvixi/jrnexzxsJDtRl4meD89m63fnqVRsLX54giO2aqoR8QhJA+ddmK4w5v8jdITfEbywb4L/4xc7CMiVDuimZB4pvkkQlfGqlPc6p/PDy6N8P8+r31UL4Fiys=,iv:P3TZdCsNMRM8Lilhyi/0DNjch99cc08MXbtXyOWDag8=,tag:zPvNav2XGzNSRZp+G4uj1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
