apiVersion: v1
kind: Secret
metadata:
    name: minio-backup-secret-source
    namespace: platform-secrets
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:rpRV5H2jg9Q36w==,iv:rGJoLYvP7ZxTQzeDr4M5yh1LYgGZWoAurdBvKS6Ycio=,tag:AsMlnzVbR9AYJX69AiN7EA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:ejSU73lWXLfIbLHL4Q==,iv:ee/HVkwZ7Co5vJY5vyITsxOKOwPQ2ghJDahFBWB1Ztw=,tag:6DfKo6NmeA6EmThNxcAUcw==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhanZOQm45a0w4eExLSk1n
            QjdhRWtCeUREVmRQT1YwdTdwMzREeVZLUzM4ClJIMUc2dnFucUNSTVRTUjRRZnZH
            bHY4N09TdGxVYVlrQXl6NkNGL1pNeVkKLS0tIG9hR2lpLy81SkZNR1ZLcWg1V29N
            RkFpYzFWMW56SXkzVDNZMk85TTVJWW8KPJn3gbrqkAd6AE1IrQInVyY7yX4g7DOU
            Cm1AMGeXYx43duw0dP8LtZpSLNeCY3ZMmGjUPBPMnUmMypJaW/Bp2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T16:38:38Z"
    mac: ENC[AES256_GCM,data:Kyz1NMlgUM4ri859O0t+qECSU9u0hph7R4QoitazdZkW6hQDBTrVYAH4S8yuaVN3MLbYvjMs2K1HnrB55mFMo42/Wx6HlyhetxNPc968nhhuhRJTU+Y7u6cVP1u8QTAfmEPJQ7Nn3+XZKHdSRnPa8LkEOFlNnUHD4VuQf1I+06g=,iv:a0zDfnF7pJInfjSb3vOvwwisKGcnv5AfebR8GRo1HcM=,tag:E8QdXGLFplq1pDIjjzgZEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
