apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: platform-secrets-generator
files:
  - ./argocd-keycloak-secret.yaml
  - ./backstage-db-credentials-source.yaml
  - ./backstage-github-app-source.yaml
  - ./backstage-keycloak-secret-source.yaml
  - ./backstage-secret-source.yaml
  - ./keycloak-admin-credentials.yaml
  - ./keycloak-db-credentials.yaml
  - ./keycloak-platform-admin-source.yaml
  - ./keycloak-app-developer-source.yaml
  - ./minio-backup-secret-source.yaml
  - ./discord-webhook-secret-source.yaml
