apiVersion: ENC[AES256_GCM,data:7lg=,iv:iZowYR1UoInT0blG10LsjDqJ8ecoogW3catDI69VoWk=,tag:0qMNmfKgSrx427+CWFVzWQ==,type:str]
kind: ENC[AES256_GCM,data:IfaJTdm/,iv:Tbi1j8coGyDkPsozONImFuKaY+MV9hckTxrqFTUDzEY=,tag:cjTc+bmuV/qJ0RLMD8maZA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:msBVC3ZyIYeea0HCc8gFewWhUa9KIHnBYBRWr/A=,iv:68LOkMDuLKw5HxO7A1jwsJkwntoxkVOwZ9nfeqGXe9A=,tag:aeQO7pSNe7DHGCiviHJPdQ==,type:str]
    namespace: ENC[AES256_GCM,data:iRm/FwMW,iv:VfCBk09rMjqHP2ZpTbngVhZPy8H5q11S/rzTuAd/Aa8=,tag:/UswtsqgVoP0VAm91EJunQ==,type:str]
stringData:
    clientSecret: ENC[AES256_GCM,data:elC454bIaeMoOvvOU99Y9AJe7+873ISjYfn/m0T01VI=,iv:RB+D3Hk+8w/cb9z/hGrj2fa3zw01SjC7BgpjnWgO/rI=,tag:wJj/N1QrxgMc79Qoui6bHg==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENzhOLzlLWmJnOWxVUEF1
            dndlL01FdDN0UlRvRHdXMkpTdzlFaGFCZHlVCmhNTzQ2cjhoS2szSEJPSG82VlRi
            RnZiQlgvc2FkU2o1Y0J6TDMxNWVEY2cKLS0tIFljbzRMd2RQTFVwclBvWjE1Yk80
            dE96R2o0R0dsYjE4V3llWUN0Y0FpNHMK9SrErxHm0hbqYHoCSUKNA+zesUgUrvqF
            TytSRJEORHkCO1kRRaUW0j8iimHgPHl2gqFNF9OolJfujfuuk6tFDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T23:01:54Z"
    mac: ENC[AES256_GCM,data:ZWp1nXc7vacQ80UtOH9tOYZZyrftkXNOnWdNcNq+R543TxYae57xThCtIVBtVSBHNaE8ps44eki5ZEIrAe1HQLV0vI1CC8Gfg5+SHX2euI1U2owOpGEFp8/J0H8hWqSJ2b4nOo4fO73FT5e+Hg94f8n4VMpT8doB3lOPWefdnPU=,iv:/z2IHIFNtTwjXXZQJzsXup//pTXC7DBPika7wy+zTmo=,tag:CPrcLht1bz+GeOVKPJ68EA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
