apiVersion: ENC[AES256_GCM,data:T9w=,iv:k3ovdVRpguQZs3sh1hkHcChMOjwzaEcH5zkKYpVKG4E=,tag:1L/DmopZuY4DU6rzqr542w==,type:str]
kind: ENC[AES256_GCM,data:3vjcc6UL,iv:jof0f2vbpPTuXdm/OKsWUGDe1sC/ZSuu3BScwMd+/I4=,tag:7JazSPBJ7VM8HpvfPt87vQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ntIahtmJY0DmIjaeGazvnzd65fRYGLgUKcWOZN8=,iv:dLO3znobLXN8a7I+Q7cYj2X8B4Qnmqv1gxfKcCr8hFo=,tag:0l3GVAJXs+3ZCedNkPGyhg==,type:str]
    namespace: ENC[AES256_GCM,data:2ZaLqgZz,iv:2TV8Wg5FKD02eSrdo+Mcn4WMitcUkgFkV/pvbj3r7AI=,tag:MuOU6ZC2uEYRIQFZ7qkZuw==,type:str]
stringData:
    clientSecret: ENC[AES256_GCM,data:cWPCD7QsK3YyiZRuaoTcGc1g+eFndCJHMxmN/rR9w5E=,iv:LPGfjPtkTzzu7vzGWZJ8dt3qfaL7EmDc+LDl590HH9s=,tag:/8CtXf137xjsxch3J0H7RA==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNnpuTmxxTktrQXB3YXhQ
            QjZwTXZBektsQ0R3TXkrZ2huYmRMbzBqSVNRCkFNVXY0NVFMUGY4bTJoeVNBNnZK
            c0dtbndwL0NOSk9SUmFHNzVwWExlSlUKLS0tIHNIZ1hhdjlKVGlrVCtZSVBac3pE
            eWNjQnlxOThnLy82U1FBNElGRWpvdjQK4e+MMizN3UB+XA46Ct2tRFsgYiAgiAPN
            pAfrGqU6Qlff5KYQ0wKYGZ/JZZFVFM8QbjVEebbc9UjnmELWK3ug1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T04:21:22Z"
    mac: ENC[AES256_GCM,data:hroJFSqjik5O0rBhP2bHH2jkcoHwXBCKXoWjqVix4U80YdIuqfr2G4n+uU4Gj+WEErK3S7TT5odOR8b6T2WYIERXO/H9f2NPiyT+vM1IwAnXfVOwDU71VmMbPgCaSPOpmEB/W1Gb4MAqe+DZu8Ac6sIUBxJ4Lw3YTFt9rsHpTqk=,iv:qW65Tvq89kGU7uETsHXTL47ovji6uULjy9ETeFr/gfk=,tag:J7PylM5mUp7Xrwy5ebQYMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
