apiVersion: ENC[AES256_GCM,data:jrM=,iv:bhcYiWNmC1jwo5tz7gw96qKwbc4GWa25RbxRmfJQ6os=,tag:Hv/QeEy8R2NvVxPMAikg0Q==,type:str]
kind: ENC[AES256_GCM,data:XCjxAvWH,iv:H0KAamnT+gSTJNS/NpY+KJMhg5DOsMnS7HITEYvlzfM=,tag:NaPn19x6BmBLwTaNWoG6Pg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KSCoR7M7WDbfc1cOW31CbX0YXigNPfjGwx9JA1JXzY4=,iv:2re2Sdven5+sNKnfuznfxcJDoWJRdJ8AUPdjTCAK6O0=,tag:JvC4/c0F++T6iIHveFnklQ==,type:str]
    namespace: ENC[AES256_GCM,data:+Al4B16A,iv:jWyN8dBl2GCcg7doW5lI2CzVX8CiW1G5kCi1TstJW7c=,tag:9IZT/t06IQABqeAhg71KUQ==,type:str]
stringData:
    clientSecret: ENC[AES256_GCM,data:y7oAg4fY/0F0Le01vZ4B0UdeWdNZj90Ip0QMutvnf60=,iv:LB9sNyGNejFQHjF7wNTf6a0V5w5yEUKYQNm7RDv7jvQ=,tag:RrDv7b8p/OCEuddkMfOiqA==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNDlyWDNOZEpzSlRrc1k0
            RW9TbEtEMndwOEtQQ0NDTitSdE93QzlZMUNrCnQrZ05peGQyd0pkMWlNY1FiZ1I0
            WWQvSkVOdzlqU01JS3Z3b05CWEk3LzAKLS0tIG5WZUF5cXoxT2hDL2ZGUW0zS2xK
            NjJEVE9uN1pZNGlDR0N1d0IzWXhmNVUKM7J7S6JjiGHZCzrpyoinqzljTKI0+c3y
            k4qNs6WP49lNVpr9tH00b/cl/YNh0KhsrXNIi+ik/j1x0Qte78bSlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T12:24:37Z"
    mac: ENC[AES256_GCM,data:NnB1svqVd3geb8j0/cN95ztjbQp4hWWFs0W6tuVpTkkUaEGWRi8AD9Q2iHv5CRF8Pg2exODRaptadkZaKuNHT+5hNYbhXff/IvMnVAa486wBIe393hh2SRKsxUXOW5bw/jMj0ylYDVI0mfWr2xhkQNy7/oz9s9iTEk5DwNFgR5Y=,iv:j17ml0TR4yaZk2V+3cISCkR6yLOyikhGB4luiWyOHsQ=,tag:01RbuxAfa/qKonldfx0YCA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
