apiVersion: ENC[AES256_GCM,data:p7o=,iv:7or1DciNfeoytF8Kio4zR4wxWCrgGdbhSJmEEyGFJ3A=,tag:as22FOQyqpg1DxB5cZFvDQ==,type:str]
kind: ENC[AES256_GCM,data:B7D742Z6,iv:zHpV21C+m6q/jqdOM9gl3XXOndddu/CjqHozCM3f62s=,tag:OiBkxyXIhm5r6cKOPwJQcA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3PxIfmoT57CFBYQu+5pI7sG09jBM8w9VP/ES6uObow==,iv:eZi1Xg8kWB3enjvvtbSxWfLakw91GvnILUbs2zwR4Sg=,tag:J42f4fKVqa4xcJ888bUkAA==,type:str]
    namespace: ENC[AES256_GCM,data:wq4qCymP,iv:Ue6M1P7Tc8W74zkPwEIxGctomUCsnPNEeSPn/6MVNSs=,tag:zfsTC7M9JYQgsuMem3ZtHw==,type:str]
type: ENC[AES256_GCM,data:ZgsLNWPn,iv:7TK8d5GEkeXr2Vcx1ATYu+OSE2YxBDeCBXJcz6xFLbA=,tag:supe1Pw0j9B0YJr5Zs8Fyg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:CGjt,iv:xGrEsTqPNDrfeISHKRAzQT0t39LYLK5dt4o1wuwAsMQ=,tag:OouBaIn9gvRnbYTRna/v0A==,type:str]
    password: ENC[AES256_GCM,data:Z96MfhMsgy/NJRmPHfD1jA1hGSo6ce/EmZqUAuenO3s=,iv:vMpWWLr8wicRRvrKdYv0ldBJF7jpq7z5b1gkCdrEfW0=,tag:FmwwN5+GVOFpLLY+vJ8xWg==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TGxOaG1tY0hCK1VCZnpY
            YkNGeCtkSXU4aTQ5L3loTTZZZlNGYTVBMGlBCnMyT0wwWUJLbUU1S3g0OFZRRnhq
            R3o3dU9veTU5WXlVYmJqSUVteE0zLzgKLS0tIHhDaEJpbnhocHFab3VsZ2dWLzRJ
            aVJBdzU3bTlyUStvL1dWVXhqSE44TVkK3ytpMxwVwp3cbu8Pen40x70F1VSUXe7T
            qcm+ImaDSRqLLs2RAvSjTzqaNJSHs3Comm78cGxImVzil65rH0m0Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T08:48:18Z"
    mac: ENC[AES256_GCM,data:+cB8fPRcaJXiS+BLsVzJg0+XDRkBIgMJyL0X0yxgiXvJXs/XDDc23epXtwBLvTd9XJydpvKqnVYlMqpy3MlwXKPI0MsyUN8vxUWzcDshTGe1EFcl1hj5Z+sMBr/NpdFpJOrbU6X1jKENAdGHl3nyy5t6VuIXadmgGBAGbfN52V8=,iv:Pgtoo864nahYwt6XB/YGlW4ZEMsmvzacc+CJ91hKpKg=,tag:QR/PI5Gv2tN4R9PpyKSkCw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
