apiVersion: ENC[AES256_GCM,data:das=,iv:7ex5RfTrwVGjJxccYpedYPdggrtOdgY6ktLeNvQDiAw=,tag:YB8oWTWRx549rxR7zcg8VQ==,type:str]
kind: ENC[AES256_GCM,data:k/7qbahp,iv:3sm/y2y4SWBIAHmL7e0YNSCDusmDCuwtYxrJgzdJaGM=,tag:H8x8QpHUNioAmKeai8jz+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ucPNf+WoLhSS49qZ4AS9QXPSS/CI+Vk=,iv:1UjzvhJEnNB1CBmWYV0+Su69Mx1wqDqkq88jPfT7RWg=,tag:3UOAa2XewDYhqnWS15IO+Q==,type:str]
    namespace: ENC[AES256_GCM,data:IF/ePk/Z,iv:k9nmBb48Okoms2Fgdv/bftK9+yafjxKTia6BORVe5+0=,tag:hiTWFSLdaVNf5zFZ3BZblQ==,type:str]
type: ENC[AES256_GCM,data:W4m5HB3k,iv:zs9uR5xYEY+1Rj4MDJqrfa1ocVpgdvyOSln+kKsxbos=,tag:nyStAnVtG4e/G5KVTnOobA==,type:str]
stringData:
    BACKEND_SECRET: ENC[AES256_GCM,data:OJJvy/t6leKZUCkYELiY0Ujw8K83xO+rzFpqnuhlP4C6Bevkbl9e8br1PtVigEAlYX0Ze1hyX2SSXHGADFm9GQ==,iv:hfbywcUu+qgAJ6ucSzyuWmYrQVCK+wem9KOYRI04jmk=,tag:G8n+7WTacaQwqjpFqADMMw==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxblhPM3FJSTM3UnptNEtF
            RmNET0pCcFZ5SGxhZEhDY0lad3VtOWlKN0VzCkFBOUkyS01yQlR5NDdnZDdKZ0pm
            TWRzT1l6NC9LSjQ0eGgyQVErbEpsOHMKLS0tIHg1dkNNS3czTkJNVWVldEZoY2ho
            NzNZc0lVL2RWN01iNThCdlVxMGd4RHcKXiDQpPIDsVwcdj1eQ5EvvyF8cmZBnlv9
            DpGbldmXD0fhjKp14JiuKdAsfdoyG3Q1ly4h3Et+zl5+nBz7lkwFtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T08:48:18Z"
    mac: ENC[AES256_GCM,data:xsrFwPQwEPIpqLxoLmuIVDxAdQmDzkP6/Y1xeku5X3vOkYc6C+pOIWUXkV9ca3hY+K55/ZXuO1vDp7wPo770NaG07AijWqUGRG/Xm7UBP1C0gZeRM58yIGsSe9H08zAAc4hqHjEUibAkR9OkByG2fO2MBwq8Twp1cIJ9n0Ko0t4=,iv:P+DWVKcpJrEcT1wRea4KYxC6Hz3MODyZX/+0w81J63o=,tag:4MYvcqIKsBknyax++6nSXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
