apiVersion: ENC[AES256_GCM,data:5xE=,iv:rtmATmx/CY5GzcPryuVRVTg1A52utT8lDykSA25ILA4=,tag:kdcZ0MjzFw+wUKnYbNLlgg==,type:str]
kind: ENC[AES256_GCM,data:BLoMCFF9,iv:IED+/6nr0qdYo7E/ENowh2CNd4ZFU6F0qaU4NBerK4s=,tag:X2DFOwiIML2UW3VWsi3dQw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:K94Gmb+jgpO9iaCnrQ/lZnbHpwyNKrlC2v3fZwk=,iv:wbW29WDpqz69gVq+GQxNVanzP0iBgCCoHUssr1NxoTk=,tag:FWlx7hvqX4ATTq5Mao1k+w==,type:str]
    namespace: ENC[AES256_GCM,data:zHFDKrGZ,iv:6E8YMEK0XQUwG4q0Mm4KcVDFKXBeD6qT456MBKdjv+8=,tag:rJRyi5qX8seYTfNUz1QksQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:FwZnBy3ZcnXTVRHEWp+u45pRjkBuqP3i0LGkrNrc7APYFHd5IUcmZw==,iv:zv+2sFx96hRXpifg+nK1vmQ6WPpnHdCATxYov/zJTdw=,tag:t3gDTuVb+wyCNqEPon8R4Q==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNVpwWTJkU0xuUTZ1VHQ5
            YTNsYVNrVDAwbW1ZcU9oTjhXdllBQlcrajFVCmZQQ1BCNEE0YmVEc2pYUGFkaFJS
            QWJkKytqN1FIbE4vY0xwcGltK3pFZkkKLS0tIDBJZ3lNdTNTZjJKeWRhalNMZ1JD
            KzlkMjBYSk11OFFvSzhzbWRqTUV2b1UKoL7yXc6aNCUtXT0FMScVbCKYAILWsOBn
            wo/kldEElCF13/yqWzRZa6ikCEcwm5NueoXICzbX8LjRbdBufif1jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T14:13:28Z"
    mac: ENC[AES256_GCM,data:q42Q+hqfURbxjWwlLOA6KuZW9Q7Xx0sn7gb7kzjAbWUFQgahA4DXdNXmP+b0t041nwS0nxVCAuUjBd8zZezrRpouZ/FtlbnLl7LmyJYwLIuKCXKTtYEL+UifubR4uR+4hP5MKMSU5+JzPhEjrEAdI029BMI/iqHxm68NnKjlsoc=,iv:Tan0zmY70kbUEosDXSXPbzCUOBOYDruJD50iaVpgGEY=,tag:5dQU58c+A4kmJC8q4gRW6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
