apiVersion: ENC[AES256_GCM,data:YVo=,iv:6LS/eF7XmcNw47o/O7aO30aR/uTtRu1y5hz6WnQ7020=,tag:qniAoL0ktI+xFAeY52VMSQ==,type:str]
kind: ENC[AES256_GCM,data:6NU6NWVS,iv:xzZ2TJ/evonqiiL9n3DHUxVC95Qp/uZKK548eyWU71o=,tag:a9apkiDfztWUQGnwjt8laQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XwK2zqKZ7zY=,iv:2PvuKv8diHkpj/3I6rusk21iO7aHnsKcbvc+2+pGBh8=,tag:P8tZzFoMedFrw0OkTBjhKQ==,type:str]
    namespace: ENC[AES256_GCM,data:SItGAJMi,iv:GzZLt59S6txJdjI02sMdMfKWA2M3rqoOv2qeafM52dw=,tag:c+CXrQNyCUzdl4b4YTqDXQ==,type:str]
type: ENC[AES256_GCM,data:4JNi6b7L,iv:324c8ZZvfhy2qIxUInbIjYu6Jdux97BhdIV9CopPxP8=,tag:clET4gLQuViCQDUwlhcheg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:RsSV,iv:l3fY8pWPplYDt209ru45oCmjlDXueIYbA8PlIKKImDk=,tag:387Hs1Fhzvpd8IvrZGRZHQ==,type:str]
    password: ENC[AES256_GCM,data:sgRV++gU5gs6CLsUBjhDgqAOKT70TN16Vblk+n4u4sf8zNZcIuXf2g==,iv:ppfpSla6mKCf3cG4JpSeyqKEkkdW0/S4XzVtI07ySic=,tag:qSDyqYPUzhO8Ay/XL8L6Sw==,type:str]
    email: ENC[AES256_GCM,data:+hD6EFAuwu4MPopvOzupvMIS,iv:FruJ3KKwkI4+lAUB5cTVArK8YN49/Oa3Mm2vqo8h3kc=,tag:gJ2zosasyIzP4+PHdf4rhA==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMDZkeGhrTmlZendYME1v
            akRuVlZTbWdaMEVJUTJVK05obTVXSFFQUW1rCko4VFdZYjNKUjE1ODFLaTlzcFpS
            d25IN2xaSFRnWTRVWTU4WUx4YlhxdFUKLS0tIHpMSlI2SjRGa01IWWtEK2s2UkRu
            VjlzWjJsMWc3ei90d1RGdEVIWUdlOWcK4BuAhnGShfK4T7u3wk3amm/AX1FN2Sb9
            QsELp4LUyv+6I8meR/oveMpvnMQQIE8Lx69sFQqAVnvVwQ9g1PdYhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T13:56:04Z"
    mac: ENC[AES256_GCM,data:o6e/Z7i6eDwqym4WWQSSRMpgyPzCMe7B6FhZcyIj4ywYmOiYlynIv4pNC0x0jLn5NRcI6sn0f1CRcoL+9ayu5h0qA/DTypV6e38sMZfNBCi79pMezKaaGXFrOYHvNJx7OKUe18tw9NVbiPFqU5tG7w+LNJVzNYMvqs9eGTvXvfw=,iv:DXi0flhE9NSI1D2bTDM22x+RfbMK+oUAa4EpBJv8eFA=,tag:bRYkvIcUPi6aM8UksFfA5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
