apiVersion: ENC[AES256_GCM,data:Z1g=,iv:JJFSFf1/UjND/6VLH4ViXeEg5PIoSdMZb9vFikjt5/k=,tag:N6xzWEWj4X0Q/yRn46MbEw==,type:str]
kind: ENC[AES256_GCM,data:DWgH0w8k,iv:K1ggHNrJuy7BE94C+ljzprtNh9OdnV/Iv6H7vEvQPy0=,tag:yTcSAe3OXfTKsGJkL6xlUA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OaSaquqJU6uacPq4hGUMocEdx0zvo2nHsl2TxQ0O,iv:rxxF60H2mzVd0ToK+mYGBQY6L5kOVnY9mppQiwucszs=,tag:HKqL4TiF2DvKddKJgPsjjg==,type:str]
    namespace: ENC[AES256_GCM,data:oedZP+8T,iv:vsZ36c3demhT8Qw7rpUzqE9xchGwD2KFMnuGDWgqFDQ=,tag:tC4BpcJWiayOR/mW+sHJ5A==,type:str]
stringData:
    password: ENC[AES256_GCM,data:oGPuEzGiN50=,iv:O/BcPKnPF61biEQxKEiXrIcdEmxccmhs1mRSW6MSwi4=,tag:cNGRtWPopKVbHSFgMVJRfQ==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQ2hFcjhmTG1DUUwvVFdB
            Mm5RclpCdFJEdWxQRzV5MFF4SXR3WElOY0JjClJQZmFCY2Zub0F5SkR2eHRmc2hH
            ZjhsRVgvZC9EemdGMFl4QWpQWjZjL2MKLS0tIDJpVGZTem82c1puaVNmdUxwd1dy
            UCtNNm9xQ0kxU1ZqQ1ZpZW1pM0huMWcKQePu2h3DJciCicvxdq41hy2qRB78qhq0
            ljZXRfJnLBsjMz8k5Na+4rBN6eiLIgRrtiGapFJSFE/Xy2PAM8p3Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T05:46:36Z"
    mac: ENC[AES256_GCM,data:7f4PMojrLYWBi4kYgs7QnHFBKhU8Y+Xk7AIb26x9tnaTv6ty2xb8xNRf9VQ7OrOvIS8SaedTIC/BF2NnOS1Dkb3bJ4R/7BByV7eWeFPmQD+V8bmoRDZiaXrZSCuwA4EGzwTHfWGw2s8ms5li9+8uQpJ5tjDkAY0lngLRTHJsDUc=,iv:uZWcGAS5ib5E7dYbCKHq8Wc3y3l90Y3i9LZlHBmEQ84=,tag:TrDF8dg9E5wO3gxAJ1IRlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
