apiVersion: ENC[AES256_GCM,data:39w=,iv:GMzdfvJl0RCcBAKjxh/yyuDJF8OKOKa+aCP9xVHFiA0=,tag:qZMdsPjiTwc7O8q2j9UDdQ==,type:str]
kind: ENC[AES256_GCM,data:4eiaHoSk,iv:HJBAQ3JnnZL8FERGfgoU3CDnUqLIpEJ8YPHTt7swG2w=,tag:4bx3tYpQc6ps1SFuP48fdQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KiTLEWiaZ2KefMBivB1s8pL5eBnhYsGlXDVz8P7J,iv:fljcWvcJK/e42h00jgQcpMPVa9H/Qg5C1dqL3fU+gdw=,tag:n3HEVgEZlFeFBxLdpTFHlQ==,type:str]
    namespace: ENC[AES256_GCM,data:MCia6oMt,iv:8hAOGyIJw06oW+5mJ3uAmfVhtBgVjl5brFCtmGmvKvI=,tag:8TmZC2iXTwAsupiZ5YhC3A==,type:str]
stringData:
    username: ENC[AES256_GCM,data:MS5aDaRsCYE=,iv:klon4PNjsVrvBsaQ3fHx6E8/6wQHdEM8v6UI2M60Kps=,tag:DSzdrmnKOnTzb0atSqAkDw==,type:str]
    password: ENC[AES256_GCM,data:8dtqPNxQreZAGfq58oa53F95cuE=,iv:/Pv56AOSxs5EQu+qDYsRGkdm9J7jrw3zveF9XLJSkWg=,tag:SqcE8sES8WsiDryzTDyXtw==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaXJBV25KZkwyQ1BTQ0pu
            MjA1ZXJKZ0o2bWd0bnJuTmR3eGExdjJYd1JFCnhKTWcyTXVKMXVSdWRpK2dRaVBX
            eG1HbXR0KzBzU2NWRlAvVlV0NktJVkkKLS0tIFh5b3c3c2dZbnVaSE43NTNrd0Rq
            amZXbXR5cFBWNzB5OEYyczhjdk9vUnMKLQPFZMLfpCDzpxqbFGm5SLVoHiQVBzeX
            ba9VWi7CV+B78COe0M32Z1p+ztGMbkM01Ewqq/haHityRxXKTnFpsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T21:26:53Z"
    mac: ENC[AES256_GCM,data:zD0Z47lnldeT9L44yml/VprHs/qicd/6ElbjTKJl/Iei2GybqqoPZpilpYhGr2ZJXrSkguJx8LNYG9IgNXKNx3MdV2rpjxg7T2uV89N8r3qA7fkcunJvdnF1uNPUEKtr+6m5mskoTNlkAp6i8XOmmrOabGcLRWKSilQsTbq5u3M=,iv:rtifwSb9LlMus1zgZGCPPmkdoXzmqo+nfdDghCzqIaU=,tag:92zoe8poPyFgemVPidXMGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
