apiVersion: ENC[AES256_GCM,data:y2A=,iv:BLqhefNcLsdJ+On6xW3jnfo+zeYw5GtThrlM3czesXY=,tag:5mdNdHpDl9KQockU4pjoaQ==,type:str]
kind: ENC[AES256_GCM,data:lq/EnrTC,iv:VhAjxWS7ZwEaXkg7YPqc/IeSf16OGgJPh2uNzPiiZho=,tag:6TyyxLMEq8oWLtiw9jk17w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:16f4ARonN2G9t0wcSwy3tk8yoTCxs3ySNguQSpSUaidS,iv:VnXJwv6cupmY23W/X9pQ6zh7qwBxwSSKaYUJA5bOc7k=,tag:phIJYpekv7uTgnhkdzuPlg==,type:str]
    namespace: ENC[AES256_GCM,data:DDG4Rf0+,iv:L9uHiXFnW6VtaGNbpwhWkAwyYAStRm8JxbxleJ6dD20=,tag:0/6hASvAW2I8MZZBl011CQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:4Co5Crx/lA0ms6P6QHmTacuTpyUvX0g=,iv:bHn1jNzjZCCgVWG3JvlK8Xpi3rQIcQ+LKcbsTGCj0rc=,tag:onm9m/mg9JMymz05mYP2Bw==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNFpkb2FjK1B2N2FBalhF
            T0wvM3BHUmdYN0g2WG1CY1VJbHdwWWFYcEUwClNoZVlaeStabmh1ZGg4Nk1CQUIw
            WVg3WnlRZUg3UER0Z3drQnhiWUhXLzQKLS0tIDlHSGRmVkN0ZWpVcGd3TFp0OHl5
            Ny9CeEREQ3BXSjRmK1VKdjNhMkU5UkEKUOEFgPKfPgnyFtRrfPU+8X7DrxViU4gS
            Uxh98ZP3GnGMR3N4hfaZoK37GLWkACoQ/ex99iUA8xOp/o5XNwP3AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T21:38:18Z"
    mac: ENC[AES256_GCM,data:Wn0q9Q7ipjSUnZkRlsTZRdAnF5X0vJj3nlBdcnMjtfcHn/JE+h8FcCIgA2TF/Wj2WkAwefEgZqA496KwK2iGwUXWhyc+zGkCJYWlZ8YFK/ekXmUcwMMUb+A/IcIBA85YZ61+nzctuMzmRI8OVzsA0b+CfjfAa7iy+wXpYl4ZUC4=,iv:uYenN8En0jJqOYAcUUENF/2K3c5Qfll+2R8AkkxbxN8=,tag:LK1ILgTwmVoHFSpvJfBPMA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
