apiVersion: ENC[AES256_GCM,data:B/c=,iv:PCE9gXW3nWHQIWI6xIpTTrArje5sgebZvDe9RUyqwPo=,tag:m02LVTDsnzgmeFY/r+SuFw==,type:str]
kind: ENC[AES256_GCM,data:K5IwM6Tt,iv:hg7cdaKinIboHgYeHa8dg3xPkLX7QjeWFHmhFXKLxEk=,tag:zvTw3XQHs0HRIItB6OI64A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Wki4dF5a1XWogQ==,iv:x6XCTc5qfQu7GlP2FXSvGIkLIv71+zp9ylxIq6nBtRI=,tag:3peWj+fd7qelMxkWImFing==,type:str]
    namespace: ENC[AES256_GCM,data:DJAGFwU=,iv:3leC/SMhIi+X5OJoy0ShqNp4NsUSEjQy6dT4eNhIgDY=,tag:Osge5ymvspVY+NRMiRhWTA==,type:str]
type: ENC[AES256_GCM,data:dht9jTZa,iv:QSmvFlP28DpN9jB3e+0jXCpsO7wIguBBIkM6sGe1vEQ=,tag:QOUrsQl7CxoFAENgaOl+ng==,type:str]
stringData:
    rootUser: ENC[AES256_GCM,data:UND/aVMJ4fBZZQ==,iv:/ttmJszeDuHn8f08kgCJzq0vbc3QQBoP5NFUKVzzthY=,tag:1pM27x70Fr12FHie+CtYKg==,type:str]
    rootPassword: ENC[AES256_GCM,data:LaqVFtRZljv66ppBSA==,iv:oPiJTLite0EAw9KV7D5/e8YL3n/tpdU5rLts5o7v21g=,tag:xyrY/KDtUDOmLZf2+A2GCg==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkb1RPZjRDN0NDekNubWVn
            UDhxbzgvblVrSWJWVFdZYnczWTViM3N0cUJvCnVWek5lTlAzei9PdDZ4S3ozU0p1
            aHY2Um9qdGFCRDQvT2dwcndhQlhZZ0kKLS0tIFI5UFVrT2dWL2tFTktFc3Fzcjc2
            UVlaK291Z09iQWRqbFZjSHEwbkxSNGMKgO+xnO0xE12VfeYKqaxmzfoar8Ma+or4
            nNsVgaWn5/sENheNEj1fVrMluZBn198+dV76B0t7dwDOJRRhqWV18w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T13:56:33Z"
    mac: ENC[AES256_GCM,data:QvmdwHM+GWqluP8pBeuyZuKhQ+K8BFRc8NS91xWqB9nwOLsPhP/sI8lu4eOl79YoPHujNGgs88sndhZ9yEU6Ox53Cynff+oQQwiYdKH9eE9iR55sFW8dO7DICv8D0fjuAxAHYzNoZmL3IBy2G0sbVgiODXyBxwKrfAHgaoPxAQ4=,iv:+XiD45b2+al6vPyTvNc7peCwUwGlRH5RFP2jDIChEV0=,tag:VUKPcAVFf8mREbBxB6VFCw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
