apiVersion: ENC[AES256_GCM,data:hA8=,iv:fXVaNM+sUHc06vWyLXR+ZWh9LRq5QUzquWvKtKLwZBY=,tag:EUIJxh3bKGmOcYa3nn07aw==,type:str]
kind: ENC[AES256_GCM,data:8Y0f/aXZ,iv:anCQXmedVuxsGtTs7AlQhU1a99TKVSSs1tIqQEWrxb4=,tag:etRNo/HuyMQZI/RgZ8/6Jw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yxZDt6RRDW+eY2B8bc3tn+BJBg==,iv:rrZnYHXmmazXKgI7UES9wKvQGh9yzGaKrxN09u/hi1A=,tag:od01UXsWj3QYppYbkW+swA==,type:str]
    namespace: ENC[AES256_GCM,data:lHAjWr5NNejtEg==,iv:f4kXc5at9I7Y1QQEiT/JzJGmumT8lkkGFita+rAyTvE=,tag:hsNlT1NFKja23olDEsZiDQ==,type:str]
type: ENC[AES256_GCM,data:epi5jHVk,iv:F0YIX4TB4B+TTmUbCr0bt5+31MY6QPT84odJ9iAyRFc=,tag:qPIEqCqQX8HNaOe4AQz5Uw==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:TIlozukqV4Fv+Q==,iv:9eZ25nCRFsYlCw1FVIAwWKVNbNoy+51V3hO5QDL4A48=,tag:pE+hnaNvVY8daZ8LucUL3Q==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:5a4Qt/JxwQhnTRJnyA==,iv:nhfAKRcOYGhN72oL3u41Ce6CN9lfk/cojyicGVVT0Mw=,tag:RkY/SIiV5JqgNh2AUJtVgg==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRk9iaHRJVmhRQTE4azc0
            a2hURnRGd2ZyWkkxYjdlWlY1dkRLTytCc1hJCmIzZFUzVXVVdDhJYUVFWDRYaTVW
            QjdnNnVCVXZMY2hxdVZDYjQrZXVPUjQKLS0tIDhXcGVlR1l3bld3L0pTTHJ4OEIx
            V3ZBQTBIcFBEUWY1U2ljTEJhd2JwSGcKHVWgrubqpIPUod3e2oBJEhGv9FXPzeXt
            4b36AVRR6Qht1Z41opNHuunVfya/RaDWwt550qYMLGG8yDbbMq1cJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T13:56:33Z"
    mac: ENC[AES256_GCM,data:v746YqQRKaFOUJfctpC2RklubhwWpL8tervEdx3Fvx8kpmqw3Z2OS6wL7OrVkRKmUCZRqBtYGaR9a173hA87t4tScRGJL32U2+RyGvQYtUg3jRBNAr+LtfQAb1s5NPO1+DEkB97nZxabESna+SFiuMiPOLvyv5KGc4bxnNkRITQ=,iv:aOzElFK7ZjQES66BkH8Cg1TrRfauoOUbfd6geBLb8pI=,tag:T4nrVc0zPf2R307esd597w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
