apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-1-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ccl-labs/platform-gitops.git
    targetRevision: HEAD
    path: platform/applications/root-1-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
