apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backstage-db-backup
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  schedule: "0 21 * * *"
  backupOwnerReference: self
  cluster:
    name: backstage-db
