apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: user-apps
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/okccl/platform-charts.git
    - https://github.com/okccl/platform-gitops.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
