app:
  name: test-app-backend
image:
  repository: ghcr.io/ccl-labs/test-app-backend
  tag: a0d33c418f66d5ffe9b8448811f2a5d4a83d84db
  pullSecretName: ghcr-pull-secret
containerPort: 8000
db:
  enabled: true
  name: test-app-db
  instances: 1
  postgresVersion: 17
  storageSize: 1Gi
