app:
  name: test-app-backend
image:
  repository: ghcr.io/ccl-labs/test-app-backend
  tag: fdbdd8949383f0ba6bed1c3dae6c43b9742a208e
  pullSecretName: ghcr-pull-secret
containerPort: 8000
db:
  enabled: false
  name: test-app-db
  instances: 1
  postgresVersion: 17
  storageSize: 1Gi
