controlPlane:
  distro:
    k3s:
      enabled: true
  statefulSet:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

sync:
  toHost:
    ingresses:
      enabled: true

exportKubeConfig:
  secret:
    name: vcluster-dev-kubeconfig

policies:
  limitRange:
    enabled: true
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
  resourceQuota:
    enabled: true
    quota:
      limits.cpu: "4"
      limits.memory: 8Gi
      requests.cpu: "2"
      requests.memory: 4Gi
      requests.storage: 20Gi
      count/pods: "20"
      count/services: "20"
      count/secrets: "100"
      count/configmaps: "100"
      count/persistentvolumeclaims: "20"
      services.nodeports: "0"
      services.loadbalancers: "1"
