apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-store
    kind: ClusterSecretStore
  target:
    name: keycloak-db-credentials
  data:
    - secretKey: username
      remoteRef:
        key: keycloak-db-credentials-source
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak-db-credentials-source
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-store
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-credentials
  data:
    - secretKey: password
      remoteRef:
        key: keycloak-admin-credentials-source
        property: password
