apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-store
    kind: ClusterSecretStore
  target:
    name: discord-webhook-secret
  data:
    - secretKey: url
      remoteRef:
        key: discord-webhook-secret-source
        property: url
