apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-alerts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/ccl-labs/platform-gitops.git
    targetRevision: main
    path: platform/monitoring/alerts
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
