configs:
  params:
    server.insecure: "true"
  cm:
    url: "http://argocd.platform.local"
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.platform.local/auth/realms/platform
      clientID: argocd
      clientSecret: $argocd-keycloak-secret:clientSecret
      requestedScopes:
        - openid
        - profile
        - email
        - groups
      insecureSkipVerify: true
  rbac:
    policy.csv: |
      g, argocd-admins, role:admin
    policy.default: role:readonly
    scopes: "[groups]"

ingress:
  enabled: false
