configs:
  params:
    server.insecure: "true"
  cm:
    url: "https://argocd.platform.local"
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.platform.local/auth/realms/platform
      clientID: argocd
      clientSecret: $argocd-keycloak-secret:clientSecret
      requestedScopes:
        - openid
        - profile
        - email
        - groups
      rootCA: |
        -----BEGIN CERTIFICATE-----
        MIIBajCCARCgAwIBAgIULZb0j7ipZrefMRqX1vdYNSnhFR0wCgYIKoZIzj0EAwIw
        EzERMA8GA1UEAxMIbG9jYWwtY2EwHhcNMjYwNTA0MDYxNTQ1WhcNMjYwODAyMDYx
        NTQ1WjATMREwDwYDVQQDEwhsb2NhbC1jYTBZMBMGByqGSM49AgEGCCqGSM49AwEH
        A0IABMH6OZzEhGCodeLO3IPUdFRXxEkTsX7zD6R6n0rgOR0+uhyNntm2Bf0v1qT2
        14jhIqx3Ya5RuWYoc6B5Q/FAERajQjBAMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMB
        Af8EBTADAQH/MB0GA1UdDgQWBBTfsowSuASUlawC1/aDKOecAdBdOzAKBggqhkjO
        PQQDAgNIADBFAiEAi1Wba5p/CwESUQGxEPl6NYW/LLbTwg1BlphMFSNXCMMCIBYo
        HAbxMGSbPbFbR3YEmj6K2Gd7ATsGB0cqjTzcBaaZ
        -----END CERTIFICATE-----
  rbac:
    policy.csv: |
      g, argocd-admins, role:admin
    policy.default: role:readonly
    scopes: "[groups]"

ingress:
  enabled: false
