{
 "title": "sample-app Quick View",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{namespace=\"sample-app\"}[5m])",
     "legendFormat": "{{endpoint}} {{method}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{namespace=\"sample-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"sample-app\", endpoint=~\"/items.*\"}[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR/WARN",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"sample-app\", app=\"sample-backend\"} |~ \"(?i)warn|error\""
    }
   ]
  }
 ]
}