apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello
  namespace: sample
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hello.localhost
      secretName: hello-tls
  rules:
    - host: hello.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello
                port:
                  number: 80
