apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.appName }}-frontend
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: okccl/${{ values.appName }}-frontend
spec:
  type: website
  lifecycle: production
  owner: app-developers
