apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: sample-apps
  sources:
    - repoURL: git@github.com:okccl/platform-charts.git
      targetRevision: main
      path: charts/sample-backend
      helm:
        valueFiles:
          - $values/apps/sample-backend/values.yaml
    - repoURL: git@github.com:okccl/platform-gitops.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:okccl/platform-gitops.git
      targetRevision: main
      path: apps/sample-backend/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        # KEDA が管理する replicaCount は無視
        - /spec/replicas
        # Helm のデフォルト値として付与される protocol: TCP を無視
        - /spec/template/spec/containers/0/ports/0/protocol
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      # ignoreDifferences のフィールドを sync 時にも上書きしない
      - RespectIgnoreDifferences=true
