apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-secret
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-store
    kind: ClusterSecretStore
  target:
    name: backstage-secret
  data:
    - secretKey: BACKEND_SECRET
      remoteRef:
        key: backstage-secret-source
        property: BACKEND_SECRET
