apiVersion: v1
kind: Secret
metadata:
  name: app-developer-sa-token
  namespace: app-developer
  annotations:
    kubernetes.io/service-account.name: app-developer-sa
type: kubernetes.io/service-account-token
