apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: local-ca-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ca:
    secretName: local-ca-secret
