apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.min.io
    chart: minio
    targetRevision: 5.4.0
    helm:
      valuesObject:
        existingSecret: minio-auth
        mode: standalone
        persistence:
          enabled: true
          size: 10Gi
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        makeBucketJob:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        buckets:
          - name: cnpg-backup
            policy: none
            purge: false
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - minio.localhost
        consoleIngress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - minio-console.localhost
        metrics:
          serviceMonitor:
            enabled: true
            includeNode: true
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
